### PR TITLE
Cleanup of OpenBCI_C

### PR DESCRIPTION
**Pull request by baffo32**
This pull request consolidates my fork of OpenBCI_C.

My goal is to organize the code as a standalone library.  Prior to this, it seems to have no overarching organization.

### CODE REVIEW

**Comment by baffo32** [comment]
Also:
- Fixes #7 
- WIP: I continue to add to this branch
- Travis build fails due to missing tests, because tests will use https://github.com/OpenBCI/OpenBCI_32bit_Simulator which is waiting on userspace support

**Comment by aj-ptw** [comment]
Love seeing all the work!

**Comment by naved001** [comment]
couldn't build this way
./autogen.sh
./configure
make
it says, autoreconf not found. Am I missing something here?

Also, if this pull requests consolidates all the other changes, why are the other pull requests still open?

Thanks!

**Comment by aj-ptw** [comment]
Does this contain #6?

**Comment by baffo32** [comment]
Hi,

This does contain #6.  It is separate from the other pull request because it is a complete change of the entire layout, in case you do not like it and still want the bugfix.

`autoreconf not found` means you need autoconf and automake.  These are used to generate the `./configure` script, which could be included in the repository already if desired.  Often people with git installed already have autoconf and automake too.

**Comment by aj-ptw** [comment]
Can you please fix the merge conflict @baffo32 and we will check it out!

**Comment by aj-ptw** [comment]
Also there appear to be a lot of compiled files present in this PR. Can you please remove those by adding them to the `gitignore`?
Looking the all the ones that end in `.m4` and `configure` which is like 14,000+ lines

**Comment by baffo32** [comment]
@aj-ptw
I added those files because they support the configure script, which I included because @naved001 does not have autoconf, so I figured others may not have it either.
Would you guys like the configure script included (developer does not need autotools), or left out (developer needs to install automake and autoconf)?

**Comment by aj-ptw** [comment]
Ah no let's remove those and tell people to download those tools in the readme.

**Comment by baffo32** [comment]
k

**Comment by baffo32** [comment]
Has been done.

**Comment by xloem** [comment]
@daniellasry I noticed you merged #13 .
I was wondering if you could give the changes in this PR a glance.
The state of this library is basically just an example.  I recall I tried to organize it to move towards it being an actual, reusable library.  I think if the merges made since were rebased on top of it it might merge fine, or I could probably find time to clean it up and rebase it at some point.

AJ wasn't merging this I believe because he wanted a simulator built to test the codebase first.  Although this is a great idea, it's a lot of work for a library that is clearly still in the nascent stages.

**Comment by baffo32** [comment]
@daniellasry I noticed you merged #13 .
I was wondering if you could give the changes in this PR a glance.
The state of this library is basically just an example. I recall I tried to organize it to move towards it being an actual, reusable library. I think if the merges made since were rebased on top of it it might merge fine, or I could probably find time to clean it up and rebase it at some point.

AJ wasn't merging this I believe because he wanted a simulator built to test the codebase first. Although this is a great idea, it's a lot of work for a library that is clearly still in the nascent stages.

**Comment by daniellasry** [comment]
@baffo32 if you can fix the merge conflicts, I will be happy to merge it.

Just so you know, OpenBCI doesn't have the cycles to maintain this library. I think there's nothing wrong with this being a community-build library if the community wants it to build it! So I will happily merge any PR's that come through.

I will edit the readme to make that more clear.

**Comment by baffo32** [comment]
@daniellasry I've rebased the branch on top of the new master so that it merges.  Thanks so much for engaging this repo.

**Pull request merged**
