### PR TITLE
Remove deprecated signal handling code.

### PR DESCRIPTION
**Pull request by baffo32**
This code does nothing, and it generates spurious signals which prevent debugging with valgrind.

### CODE REVIEW

**Comment by aj-ptw** [comment]
What OS are running on?

**Comment by baffo32** [comment]
Fedora Core Linux

**Comment by aj-ptw** [comment]
Ok could you make a PR for the readme.md on how you compile and run this program? I will set up a continuous integration for this repo so we can be sure that PRs like yours and in the future don't break it

**Comment by baffo32** [comment]
Definitely.  I'll add it to #5 ?

**Comment by aj-ptw** [comment]
@baffo32 would you mind doing it on #8

**Comment by baffo32** [comment]
Done.

How are you planning on setting up the testing and continuous integration?

I found https://github.com/naved001/Fake-Board, but it looks like a kernel module.  I don't think that will work in Travis-CI.  Would it be helpful to port Fake-Board to userspace so it could run in travis?

**Comment by aj-ptw** [comment]
@baffo32 yes that was just merged with https://github.com/OpenBCI/OpenBCI_32bit_Simulator and that was how I wanted to do it!! That was pretty much the whole point for that simulator was to run the test suite for this driver.

**Comment by aj-ptw** [comment]
roping in @naved001 into this convo

**Comment by aj-ptw** [comment]
Hey @baffo32 and @naved001 I opened https://github.com/OpenBCI/OpenBCI_32bit_Simulator/issues/2

**Comment by naved001** [comment]
@baffo32 I was using a kernel module, because that way I could have a device read and write function. so whenever the driver wrote/read to/from the /dev/ file, the respective function would be invoked. 
But now that we need to do it in user space, I was thinking of running the fake board in the background and have it continuously check the FILE, and the driver in the foreground will talk to it via the file. do you think that's the way to do it? Or do you have any suggestions.

**Comment by baffo32** [comment]
Rather than reading/writing from and to a file, I'd read and write from and to `stdin` and `stdout`.  Then [socat](http://www.dest-unreach.org/socat/) can be used to turn that into a serial device quickly ( e.g. https://github.com/gmkarl/lightspeedbulk/blob/master/test/make_tty.sh ).

I don't know how socat makes a userspace serial device, but if you wanted to go all the way it can be done, and socat is open source.  Really, though, I expect that it's easier to debug the simulator if you can access it via stdin and stdout.

**Comment by baffo32** [comment]
this is included in #10 and not really significant standing on its own

**Pull request closed without merging**
